# Generated by Django 3.0.3 on 2020-03-31 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('image', models.URLField(default='https://via.placeholder.com/150')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubTopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('price', models.DecimalField(decimal_places=2, help_text='Topping price', max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Product')),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], help_text='Choose the size', max_length=1)),
            ],
            bases=('orders.product',),
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Product')),
            ],
            bases=('orders.product',),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Product')),
                ('type', models.CharField(choices=[('R', 'Regular'), ('S', 'Sicilian')], help_text='Regular or Sicilian Pizza?', max_length=1)),
                ('topping', models.IntegerField(choices=[('0', 'Cheese'), ('1', '1 Topping'), ('2', '2 Toppings'), ('3', '3 Toppings'), ('4', 'Special')], help_text='How many toppings?')),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], help_text='Choose your Pizza Size', max_length=1)),
            ],
            bases=('orders.product',),
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Product')),
            ],
            bases=('orders.product',),
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Product')),
                ('size', models.CharField(choices=[('S', 'Small'), ('L', 'Large')], help_text='Choose the size', max_length=1)),
            ],
            bases=('orders.product',),
        ),
    ]
