# Generated by Django 3.0.2 on 2020-01-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='choice',
        ),
        migrations.AlterField(
            model_name='dinner',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sub',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], max_length=1),
        ),
    ]
