# Generated by Django 3.0.3 on 2020-04-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200401_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='topping',
            field=models.CharField(choices=[('CH', 'Cheese'), ('1T', '1 Topping'), ('2T', '2 Toppings'), ('3T', '3 Toppings'), ('SP', 'Special')], help_text='How many toppings?', max_length=2),
        ),
    ]
