# Generated by Django 3.0.2 on 2020-01-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200122_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='salad',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='sub',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
