# Generated by Django 3.0.2 on 2020-01-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200123_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
