# Generated by Django 3.0.3 on 2020-04-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200415_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub',
            name='type',
        ),
    ]
