# Generated by Django 3.0.3 on 2020-02-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_sub_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='choice',
            field=models.CharField(choices=[('RP', 'Regular Pizza'), ('SP', 'Sicilian Pizza')], default='RP', max_length=2),
        ),
    ]
