# Generated by Django 3.0.3 on 2020-04-15 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subtype', to='orders.SubType'),
            preserve_default=False,
        ),
    ]
