# Generated by Django 3.0.3 on 2020-02-18 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_pizza_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='orders.PizzaType'),
        ),
    ]
