# Generated by Django 3.0.3 on 2020-04-15 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_sub_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='sub',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], help_text='Choose the Sub size', max_length=1),
        ),
        migrations.AddField(
            model_name='dinner',
            name='type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dinnertype', to='orders.DinnerType'),
            preserve_default=False,
        ),
    ]
