# Generated by Django 3.0.3 on 2020-02-18 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_pizza_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='_type',
            new_name='type',
        ),
    ]
