# Generated by Django 3.0.3 on 2020-02-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200218_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(related_name='pizzas', to='orders.PizzaTopping'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='topping',
            field=models.ManyToManyField(related_name='subs', to='orders.SubTopping'),
        ),
    ]
