# Generated by Django 3.0.3 on 2020-05-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200420_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', help_text='Choose the Sub size', max_length=1),
        ),
    ]
