# Generated by Django 3.0.3 on 2020-02-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200218_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub',
            old_name='topping',
            new_name='toppings',
        ),
    ]
