# Generated by Django 3.0.3 on 2020-06-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnertype',
            name='image',
            field=models.URLField(default='https://via.placeholder.com/150'),
        ),
        migrations.AddField(
            model_name='pasta',
            name='image',
            field=models.URLField(default='https://via.placeholder.com/150'),
        ),
        migrations.AddField(
            model_name='pizzatype',
            name='image',
            field=models.URLField(default='https://via.placeholder.com/150'),
        ),
        migrations.AddField(
            model_name='salad',
            name='image',
            field=models.URLField(default='https://via.placeholder.com/150'),
        ),
        migrations.AddField(
            model_name='subtype',
            name='image',
            field=models.URLField(default='https://via.placeholder.com/150'),
        ),
    ]
