# Generated by Django 3.0.3 on 2020-02-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200219_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='type',
            new_name='name',
        ),
    ]
