# Generated by Django 3.0.3 on 2020-02-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200221_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='choice',
        ),
        migrations.AddField(
            model_name='pizza',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='orders.PizzaType'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(choices=[('RP', 'Regular Pizza'), ('SP', 'Sicilian Pizza')], default='RP', max_length=2),
        ),
    ]
