# Generated by Django 3.0.3 on 2020-02-21 16:57

from django.db import migrations

def pizza_link(apps, schema_editor):
    Pizza = apps.get_model('orders', 'Pizza')
    PizzaChoice = apps.get_model('orders', 'PizzaChoice')
    for pizza in Pizza.objects.all():
        name, created = PizzaChoice.objects.get_or_create(name=pizza.name)
        pizza.name_of_pizza = name
        pizza.save()

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200221_1617'),
    ]

    operations = [
        migrations.RunPython(pizza_link)
    ]
