# Generated by Django 3.0.3 on 2020-02-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200221_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='name',
        ),
    ]
