# Generated by Django 3.0.3 on 2020-02-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_pizza_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='name_of_pizza',
            new_name='name',
        ),
    ]
